# Best models 
Trained on 100% of data

In [50]:
import pandas as pd
from glob import glob
import json
from pprint import pprint as pp

In [51]:
hits = glob("./results/*/summary.json", recursive=True)

summaries = []

for hit in hits:
    with open(hit, "r") as file:
        summaries.append(json.load(file))

pp(summaries)

[{'best_params': {'dropout': 0.25,
                  'hidden_size': 128,
                  'input_chunk_length': 16,
                  'lr': 0.0002486566712127507,
                  'num_attention_heads': 2},
  'best_validation_value': 29.1492919921875,
  'model_name': 'tft',
  'n_trials_completed': 25,
  'target_component': 'Value_NE5'},
 {'best_params': {'changepoint_prior_scale': 0.010785544447274151,
                  'seasonality_mode': 'additive',
                  'seasonality_prior_scale': 2.9083269883900615},
  'best_validation_value': 13.608879233656182,
  'model_name': 'prophet',
  'n_trials_completed': 25,
  'target_component': 'Value_NE5'},
 {'best_params': {'d_conv': 1,
                  'd_state': 16,
                  'dropout': 0.14,
                  'expand': 16,
                  'hidden_size': 32,
                  'input_chunk_length': 16,
                  'lr': 0.0016324890785001118},
  'best_validation_value': 31.99598503112793,
  'model_name': 'ssm-tft',
  'n_trials_completed': 25,
  'target_component': 'Value_NE5'}]

# Hyperparameter runs that were not pruned
Some runs were instantly pruned by `PyTorchLightningPruningCallback` in `./AML/model_config.py`. These are not available.  
Hyperparameters are optimized on 30% of data.

In [8]:
import pandas as pd


col_names = ["model name", "epochs_trained", "normalized_execution_time", "smape_score", "ies", "rcs", "num_params"]
pdf = pd.read_csv("Prophet-eval-log.csv", header=None, names=col_names)
sdf = pd.read_csv("TFTSSMModel-eval-log.csv", header=None, names=col_names)
tdf = pd.read_csv("TFTModel-eval-log.csv", header=None, names=col_names)

In [14]:
df = pd.concat([sdf, tdf, pdf]).reset_index(drop=True)
df.head()

,model name,epochs_trained,normalized_execution_time,smape_score,ies,rcs,num_params
0,TFTSSMModel,15.0,47.476470,10.559140,53.081413,0.018839,1135835.0
1,TFTSSMModel,17.0,28.908813,13.301110,33.343925,0.029990,105595.0
2,TFTSSMModel,16.0,34.261433,12.489837,39.151375,0.025542,62187.0
3,TFTSSMModel,8.0,28.620031,12.810181,32.824970,0.030465,104315.0
4,TFTSSMModel,10.0,42.315144,11.996192,48.083310,0.020797,1343707.0

In [42]:
df.sort_values("ies")

,model name,epochs_trained,normalized_execution_time,smape_score,ies,rcs,num_params
39,Prophet,NaN,8.750755,35.698194,13.608879,0.073481,NaN
42,Prophet,NaN,9.040859,35.722740,14.065408,0.071096,NaN
30,Prophet,NaN,9.207986,35.700744,14.320517,0.069830,NaN
24,Prophet,NaN,9.334859,35.627958,14.501418,0.068959,NaN
41,Prophet,NaN,11.100518,35.649007,17.249955,0.057971,NaN
31,Prophet,NaN,11.123008,35.695401,17.297375,0.057812,NaN
33,Prophet,NaN,11.791101,35.645967,18.322241,0.054578,NaN
40,Prophet,NaN,12.007616,35.731190,18.683426,0.053523,NaN
29,Prophet,NaN,12.085548,35.694150,18.793855,0.053209,NaN
43,Prophet,NaN,12.775426,35.681755,19.862834,0.050345,NaN
35,Prophet,NaN,12.879278,35.638100,20.010718,0.049973,NaN
19,Prophet,NaN,13.438917,34.770630,20.602555,0.048538,NaN
38,Prophet,NaN,14.612228,35.662745,22.711923,0.044030,NaN
37,Prophet,NaN,14.906626,35.568076,23.135466,0.043224,NaN
22,Prophet,NaN,17.354728,35.481728,26.898936,0.037176,NaN
20,Prophet,NaN,17.798474,34.771364,27.286289,0.036648,NaN
15,TFTModel,15.0,26.141667,10.318007,29.149292,0.034306,880155.0
16,TFTModel,20.0,25.382122,14.233887,29.594582,0.033790,24347.0
26,Prophet,NaN,19.655502,34.769053,30.132173,0.033187,NaN
14,TFTModel,9.0,27.009326,12.313195,30.802042,0.032465,871931.0
27,Prophet,NaN,19.901213,35.418013,30.815425,0.032451,NaN
25,Prophet,NaN,19.948209,35.436549,30.897062,0.032366,NaN
18,TFTModel,9.0,27.424336,11.440889,30.967266,0.032292,871931.0
9,TFTSSMModel,18.0,28.890148,9.706958,31.995985,0.031254,144251.0
12,TFTModel,9.0,28.559725,11.591753,32.304367,0.030956,68799.0
11,TFTSSMModel,15.0,29.366021,9.132409,32.317375,0.030943,144251.0
7,TFTSSMModel,9.0,28.765652,11.621446,32.548225,0.030724,104315.0
5,TFTSSMModel,11.0,29.076288,10.964753,32.657050,0.030621,144251.0
3,TFTSSMModel,8.0,28.620031,12.810181,32.824970,0.030465,104315.0
13,TFTModel,14.0,28.782942,13.674067,33.342175,0.029992,68799.0
1,TFTSSMModel,17.0,28.908813,13.301110,33.343925,0.029990,105595.0
10,TFTSSMModel,5.0,29.290506,12.459537,33.459393,0.029887,85883.0
21,Prophet,NaN,22.380980,34.724861,34.287144,0.029165,NaN
23,Prophet,NaN,22.589519,35.391189,34.963526,0.028601,NaN
34,Prophet,NaN,24.011496,35.512447,37.234311,0.026857,NaN
2,TFTSSMModel,16.0,34.261433,12.489837,39.151375,0.025542,62187.0
36,Prophet,NaN,25.386124,35.460221,39.334073,0.025423,NaN
32,Prophet,NaN,25.497523,35.498456,39.530097,0.025297,NaN
17,TFTModel,14.0,36.097899,9.889139,40.059433,0.024963,68799.0
6,TFTSSMModel,12.0,36.342360,9.725488,40.257610,0.024840,300187.0
4,TFTSSMModel,10.0,42.315144,11.996192,48.083310,0.020797,1343707.0
28,Prophet,NaN,34.113194,34.723569,52.259588,0.019135,NaN
0,TFTSSMModel,15.0,47.476470,10.559140,53.081413,0.018839,1135835.0
8,TFTSSMModel,9.0,62.020301,9.393740,68.450350,0.014609,630427.0

In [41]:
df.sort_values("smape_score")

,model name,epochs_trained,normalized_execution_time,smape_score,ies,rcs,num_params
11,TFTSSMModel,15.0,29.366021,9.132409,32.317375,0.030943,144251.0
8,TFTSSMModel,9.0,62.020301,9.393740,68.450350,0.014609,630427.0
9,TFTSSMModel,18.0,28.890148,9.706958,31.995985,0.031254,144251.0
6,TFTSSMModel,12.0,36.342360,9.725488,40.257610,0.024840,300187.0
17,TFTModel,14.0,36.097899,9.889139,40.059433,0.024963,68799.0
15,TFTModel,15.0,26.141667,10.318007,29.149292,0.034306,880155.0
0,TFTSSMModel,15.0,47.476470,10.559140,53.081413,0.018839,1135835.0
5,TFTSSMModel,11.0,29.076288,10.964753,32.657050,0.030621,144251.0
18,TFTModel,9.0,27.424336,11.440889,30.967266,0.032292,871931.0
12,TFTModel,9.0,28.559725,11.591753,32.304367,0.030956,68799.0
7,TFTSSMModel,9.0,28.765652,11.621446,32.548225,0.030724,104315.0
4,TFTSSMModel,10.0,42.315144,11.996192,48.083310,0.020797,1343707.0
14,TFTModel,9.0,27.009326,12.313195,30.802042,0.032465,871931.0
10,TFTSSMModel,5.0,29.290506,12.459537,33.459393,0.029887,85883.0
2,TFTSSMModel,16.0,34.261433,12.489837,39.151375,0.025542,62187.0
3,TFTSSMModel,8.0,28.620031,12.810181,32.824970,0.030465,104315.0
1,TFTSSMModel,17.0,28.908813,13.301110,33.343925,0.029990,105595.0
13,TFTModel,14.0,28.782942,13.674067,33.342175,0.029992,68799.0
16,TFTModel,20.0,25.382122,14.233887,29.594582,0.033790,24347.0
28,Prophet,NaN,34.113194,34.723569,52.259588,0.019135,NaN
21,Prophet,NaN,22.380980,34.724861,34.287144,0.029165,NaN
26,Prophet,NaN,19.655502,34.769053,30.132173,0.033187,NaN
19,Prophet,NaN,13.438917,34.770630,20.602555,0.048538,NaN
20,Prophet,NaN,17.798474,34.771364,27.286289,0.036648,NaN
23,Prophet,NaN,22.589519,35.391189,34.963526,0.028601,NaN
27,Prophet,NaN,19.901213,35.418013,30.815425,0.032451,NaN
25,Prophet,NaN,19.948209,35.436549,30.897062,0.032366,NaN
36,Prophet,NaN,25.386124,35.460221,39.334073,0.025423,NaN
22,Prophet,NaN,17.354728,35.481728,26.898936,0.037176,NaN
32,Prophet,NaN,25.497523,35.498456,39.530097,0.025297,NaN
34,Prophet,NaN,24.011496,35.512447,37.234311,0.026857,NaN
37,Prophet,NaN,14.906626,35.568076,23.135466,0.043224,NaN
24,Prophet,NaN,9.334859,35.627958,14.501418,0.068959,NaN
35,Prophet,NaN,12.879278,35.638100,20.010718,0.049973,NaN
33,Prophet,NaN,11.791101,35.645967,18.322241,0.054578,NaN
41,Prophet,NaN,11.100518,35.649007,17.249955,0.057971,NaN
38,Prophet,NaN,14.612228,35.662745,22.711923,0.044030,NaN
43,Prophet,NaN,12.775426,35.681755,19.862834,0.050345,NaN
29,Prophet,NaN,12.085548,35.694150,18.793855,0.053209,NaN
31,Prophet,NaN,11.123008,35.695401,17.297375,0.057812,NaN
39,Prophet,NaN,8.750755,35.698194,13.608879,0.073481,NaN
30,Prophet,NaN,9.207986,35.700744,14.320517,0.069830,NaN
42,Prophet,NaN,9.040859,35.722740,14.065408,0.071096,NaN
40,Prophet,NaN,12.007616,35.731190,18.683426,0.053523,NaN